### ISSUE TITLE
Sending Title Launch Message all of a sudden ignored by console

### ISSUE THREAD

**Issue by chefbennyj1** [OpenXbox/xbox-smartglass-csharp#52]
HI guys,

The SmartGlass client seems to be having issues getting through to the xbox console when sending Title Launch requests.

I noticed that the smartglass app was updated the other day on my android device. I'm not sure if there was a console update, however, this issue seemed to begin around the same time.

All other messages seem to be retrieved/sent  successfully.

Should mention that after a TitleLaunch Message is sent, the CLI will no longer update with Messages.

**Comment by 4reeeal** [comment]
Yep, same with Python, think it has been patched (tested both versions on the same console today).

Working console ver: 10.0.17763.4086
Patched console ver: 10.0.11763.4088

**Comment by tuxuser** [comment]
Let's just wait and see if it gets fixed ;) Thanks for the reports.

**Comment by cmccambridge** [comment]
@4reeeal is it possible to downgrade the xbox OS version to test? I'm experiencing the same failure (404 in the logs when fetching titlehub.xbox.com, and the official SmartGlass app likewise fails to launch titles/"Play on Xbox"). My console is on the .4088 version as well, evidently having updated itself 2 days ago.

**Comment by tuxuser** [comment]
Nope, it is not possible to downgrade the Xbox OS.
titlehub returning 404 indicates a change in their XBL API

**Comment by chefbennyj1** [comment]
Boy, I hope this gets resolved my M$ soon. It's been a week and my entire custom alexa skill revolves around this feature... LOL

**Comment by joelday** [comment]
Are we really saying "M$" on a project written in C# for a Microsoft product that we should be happy Microsoft doesn't take issue with? What year is this?

**Comment by chefbennyj1** [comment]
> Are we really saying "M$" on a project written in C# for a Microsoft product on a free Microsoft owned open source platform, that we should be happy Microsoft doesn't take issue with? What year is this?

I know, it's a force of habit. LOL. Let us not forget they did give away their last operating system for free and have kept our wonderful Github running the same way it has always ran after its acquisition too. I'm a fanboy. :)

**Comment by tuxuser** [comment]
Has the situation possibly changed (for the better?) with a recent systemupdate?

**Comment by cmccambridge** [comment]
No changes (still broken) here. Have received no console updates since the one that coincided with this breaking, and the "Xbox App" on phone or Windows laptop likewise fails to switch apps via "Play on Xbox" ... same symptoms that nothing at all occurs. Haven't taken the time to intercept the traffic yet and see whether the apps are calling through the same broken API.

**Comment by chefbennyj1** [comment]
I filled out a bug report for the Smartglass app with MS the other day. I'm sure they know about the issue and I bet it'll be resolved in the next system update/App update.

Of course, I get these great libraries working in my service application, and then this happens...

At least I can still feed my Machine learning dataset with the content that is still provided by these libraries... So Bonus!

**Comment by cmccambridge** [comment]
Is the bug report filed anywhere publicly that other impacted folks should go upvote?

**Comment by chefbennyj1** [comment]
> Is the bug report filed anywhere publicly that other impacted folks should go upvote?

Trying to find the thread, I think it was sent via message. The xbox website seems to get you running in circles. Hope this issue gets fixed soon :)

**Comment by chefbennyj1** [comment]
Has anyone else been able to send launch requests through the API with any of the recent console updates? :)

**Comment by cmccambridge** [comment]
No, no luck. :(
Have you had success?

My Xbox One was updated April 17 to 10.0.18362.2018 (19h1_release_xbox_dev_1904.190410-1845). No chnage in behavior, though.

**Comment by chefbennyj1** [comment]
A new update tonight for Xbox Insiders, still no joy. 
Waiting for a new Smartglass update on my phone to see if that changes anything.

**Comment by chefbennyj1** [comment]
Fingers crossed a new version of smartglass was just released on Android. I have faith that the launch commands are fix.

Testing now

**Comment by chefbennyj1** [comment]
No! It's not fixed. Smartglass will not launch titles... Even from the Android app. 😐

That is just not good. 😞

**Comment by wh010ne** [comment]
Sadly this feature HAS been disabled by Microsoft. I would venture to say that this was due to potential security issues. Launching Titles via code allowed you to launch a title via string URI or with uint TitleId. When launching as uint Titled, you had the ability to pass parameters with the call. I played with this doing some Fuzzing and strange things happened on the console to the point that that there could be a exploit somewhere. Someone may have beat me to it as this was patched very quickly and quietly. So.... where can we go from here. I have developed two work around's that still work. One ugly, and one just a pain in the ass. So for those that would like to try their hand here you go.

1. (Ugly, but simple) Launch a Title via pre-defined button combos. It works but you have to see the results happening on the console.

2. Create a UWP bridge app that is REST enabled (or WebSockets) that accepts the title launch command and converts it to a local app URI and calls it locally on the console. Create a store package and submit the app to the store (you can hide it from the public, don't worry) this way you can get your bridge installed on the console in RETAIL mode. This method seems to work fine for now, until I'm sure MS will eventually lock this down too. Whatever happened to actually owning the things you buy? For the general consumer this is good, but not advanced users.

**Comment by joelday** [comment]
Confirmed that all title launch features of the iOS Xbox app are also non-functional now.

**Comment by wh010ne** [comment]
Tux, Joel, should we not exclude the Launch call now? Looking at MS new API's this is definitely a no-no anymore. Basics functions will still work, but this library is going to need some refreshment on the new API's, as it all depends on the consoles OS which has changed. Basically now we're locked down to just key/button presses, and thankfully, Nano for now but that is changing also. This project is dead unless all sub repos are updated with new API and get to a standard. (One library refers to token as this and another repo refer to token as x. Get common. and it breaks shit) The new API support the basic still but coming in the future MS is going to RemoteDevicesAPI. So unless this project gets together and Updates  accordingly it is a dead project. Might as well just use the winmd's that MS provides. Sad, but true.

**Comment by wh010ne** [comment]
Joel, Sorry I know your in a fit right now. God-forbid you say something bad about Ms. Sure they offer alot for free, and 'try' to be opensource but their efforts are disguised. Wolf in sheep clothing. But i will tell you this... When xCloud and Project Scarlett are official, this library will be just what you get in the winmd. It's just a wrapper. How's it feel to be spitted by Ms changes? that's what i thought, Exactly.

**Comment by chefbennyj1** [comment]
I just want my Alexa to start apps on my Xbox. It's more of an Amazon thing because they haven't released the skill in Canada, so I rolled my own OWIN service which accepts Amazon Alexa requests and sends them to the Xbox.

At least I can turn the Xbox on and off.

I guess I can call on Cortana for the rest.

**Comment by mitchcapper** [comment]
Project rome can launch protocols (ie netflix://) however it is native UWP /com library only and does not seem to talk directly to the device (looking at packet capture).  Not a great substitute.  There is the graph API but it does not seem to be able to do the same.
