### ISSUE TITLE
add a winform sample application

### ISSUE THREAD

**Issue by Tranquilty** [OpenXbox/xbox-smartglass-csharp#69]
hello can someone add a sample application in C# winform.
being able to connect to the console and send text to the console like in a message

**Comment by wh010ne** [comment]
If that is all you want to accomplish just reference the Microsoft.Xbox.SmartGlass.winmd and create a connection and send notification. very simple.If your creative, you can also you Mon.Cecil to perform some tricks on the assembly and allow you to actually inherit interfaces. If you want to go opensource then you have implement the call via this library once you get connect and have the text channel active.

Nothing speacial with a winform app as long as you read my comment in #64 about the right references. You want to use AT LEAST .Net v4.7.2 which Xbox now handles.

**Comment by wh010ne** [comment]
Please close your 'issues' when done so they keep sticking around as an 'issue' when this is not an issue with this library. Help reduce the clutter. I help you no help us.

**Comment by joelday** [comment]
Super welcoming.

**Comment by wh010ne** [comment]
LMAO Joel! I finally got some humor, dry, I get it though. But seriously, I tried with examples and stuff but these two issue keep sticking around as active and it bugs. I learnt through READING the docs and researching on MS docs. It's better for you anyway's since you'll learn so much more along the way. I do welcome all new comers though and will help.
