### ISSUE TITLE
Add InputTVRemoteChannel / ir command lookup and sending

### ISSUE THREAD

**Issue by mitchcapper** [OpenXbox/xbox-smartglass-csharp#81]
Will send a PR for this shortly.  Allow for sending device commands and getting what they are.

**Comment by queequac** [comment]
This issue is already closed. But please have a look at my comment on line 21 in JsonBaseMessageJsonConverter.cs: https://github.com/OpenXbox/xbox-smartglass-csharp/pull/82/commits/738b045bd55dbcbc2ab4b8c75ab9ce56aada0ce3#r477471931 @mitchcapper 

I would expect `JsonBaseMessage` instead of `BroadcastBaseMessage` (copy'n'paste from from the BroadcastMessageJsonConverter?). Was that converter then actually ever called?🤔
